version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    restart: always
    command: --check-caps false --ISCAgent false
    ports:
      - 58318:1972
      - 58316:52773
      - 58317:53773
    volumes:
      - ./:/home/irisowner/dev
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - SQLEMBEDDINGS_DISABLED_MODELS=$SQLEMBEDDINGS_DISABLED_MODELS

  jupyter:
    image: quay.io/jupyter/base-notebook
    ports:
      - 39999:8888
    volumes:
      - ./jupyter:/home/jovyan/work
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    command: ["start-notebook.py", "--NotebookApp.token='123'"]
